# Generated by Django 3.2 on 2021-05-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RayTracing2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('delta0', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RayTracing3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x0', models.FloatField()),
                ('y0', models.FloatField()),
                ('z0', models.FloatField()),
                ('alpha0', models.FloatField()),
                ('beta0', models.FloatField()),
                ('gamma0', models.FloatField()),
            ],
        ),
    ]
